#include "sensor_distance.h"

/* Generated by tools/logging/fit_sensor_distance.py. */
void sensor_distance_load_profile_luts(void)
{
  static const uint16_t s_fr_mm[] = {
    40, 45, 50, 55, 60, 65, 70, 75, 80
  };
  static const uint16_t s_fr_ad[] = {
    3048, 2508, 1936, 1507, 1196, 969, 797, 669, 565
  };
  (void)sensor_distance_set_lut_fr(s_fr_mm, s_fr_ad, sizeof(s_fr_mm) / sizeof(s_fr_mm[0]));

  static const uint16_t s_fl_mm[] = {
    40, 45, 50, 55, 60, 65, 70, 75, 80
  };
  static const uint16_t s_fl_ad[] = {
    3043, 2494, 1924, 1516, 1231, 1004, 835, 699, 595
  };
  (void)sensor_distance_set_lut_fl(s_fl_mm, s_fl_ad, sizeof(s_fl_mm) / sizeof(s_fl_mm[0]));

  static const uint16_t s_front_sum_mm[] = {
    40, 45, 50, 55, 60, 65, 70, 75, 80
  };
  static const uint16_t s_front_sum_ad[] = {
    6091, 5002, 3860, 3023, 2427, 1973, 1632, 1368, 1160
  };
  (void)sensor_distance_set_lut_front_sum(s_front_sum_mm, s_front_sum_ad, sizeof(s_front_sum_mm) / sizeof(s_front_sum_mm[0]));
}
