#include "sensor_distance.h"

/* Generated by tools/logging/fit_sensor_distance.py. */
void sensor_distance_load_profile_luts(void)
{
  static const uint16_t s_r_mm[] = {
    23, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80
  };
  static const uint16_t s_r_ad[] = {
    2475, 1598, 1165, 876, 673, 522, 415, 339, 297, 240, 198, 165
  };
  (void)sensor_distance_set_lut_r(s_r_mm, s_r_ad, sizeof(s_r_mm) / sizeof(s_r_mm[0]));

  static const uint16_t s_l_mm[] = {
    23, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80
  };
  static const uint16_t s_l_ad[] = {
    2498, 1794, 1271, 942, 720, 564, 451, 371, 310, 263, 224, 188
  };
  (void)sensor_distance_set_lut_l(s_l_mm, s_l_ad, sizeof(s_l_mm) / sizeof(s_l_mm[0]));

}
