#include "sensor_distance.h"

/* Generated by tools/logging/fit_sensor_distance.py. */
void sensor_distance_load_profile_luts(void)
{
  static const uint16_t s_r_mm[] = {
    23, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80
  };
  static const uint16_t s_r_ad[] = {
    2507, 1572, 1138, 848, 640, 492, 387, 316, 253, 211, 176, 150
  };
  (void)sensor_distance_set_lut_r(s_r_mm, s_r_ad, sizeof(s_r_mm) / sizeof(s_r_mm[0]));

  static const uint16_t s_l_mm[] = {
    23, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80
  };
  static const uint16_t s_l_ad[] = {
    2919, 1905, 1361, 990, 733, 567, 448, 361, 298, 249, 210, 176
  };
  (void)sensor_distance_set_lut_l(s_l_mm, s_l_ad, sizeof(s_l_mm) / sizeof(s_l_mm[0]));

}
