/* Generated by tools/route_precompute/generate.py; DO NOT EDIT. */
#ifndef NIGHTFALL_F413_ROUTE_MOTION_TABLE_H
#define NIGHTFALL_F413_ROUTE_MOTION_TABLE_H

#include <stddef.h>
#include <stdint.h>

#include "motion_time.h"

#ifdef __cplusplus
extern "C" {
#endif

#define F413_ROUTE_PRECOMPUTED_SCHEMA_VERSION (1U)
#define F413_ROUTE_PRECOMPUTED_CASE_FIRST (6U)
#define F413_ROUTE_PRECOMPUTED_CASE_LAST (9U)
#define F413_ROUTE_PRECOMPUTED_CASE_COUNT (4U)
#define F413_ROUTE_PRECOMPUTED_SPEED_COUNT (3U)
#define F413_ROUTE_PRECOMPUTED_KIND_COUNT (8U)
#define F413_ROUTE_PRECOMPUTED_HEADING_CLASS_COUNT (2U)
#define F413_ROUTE_PRECOMPUTED_EXIT_SPEED_COUNT (4U)
#define F413_ROUTE_PRECOMPUTED_MAX_CONNECTOR_STEPS (68U)
#define F413_ROUTE_PRECOMPUTED_CONNECTOR_STEP_COUNT (69U)
#define F413_ROUTE_PRECOMPUTED_INPUT_SHA256 "f318008f6a0a7b97031f540fc3a52fd0372570e1bdd4820dba36226b12d30731"
#define F413_ROUTE_PRECOMPUTED_POSE_COUNT (1158U)

typedef enum
{
  F413_ROUTE_PRECOMPUTED_SPEED_NOMINAL = 0,
  F413_ROUTE_PRECOMPUTED_SPEED_LOW,
  F413_ROUTE_PRECOMPUTED_SPEED_CRAWL,
} F413RoutePrecomputedSpeed;

typedef enum
{
  F413_ROUTE_PRECOMPUTED_HEADING_ORTHOGONAL = 0,
  F413_ROUTE_PRECOMPUTED_HEADING_DIAGONAL,
} F413RoutePrecomputedHeadingClass;

typedef enum
{
  F413_ROUTE_PRECOMPUTED_EXIT_NOMINAL = 0,
  F413_ROUTE_PRECOMPUTED_EXIT_LOW,
  F413_ROUTE_PRECOMPUTED_EXIT_CRAWL,
  F413_ROUTE_PRECOMPUTED_EXIT_STOP,
} F413RoutePrecomputedExitSpeed;

typedef enum
{
  F413_ROUTE_PRECOMPUTED_LARGE_90 = 0,
  F413_ROUTE_PRECOMPUTED_LARGE_180,
  F413_ROUTE_PRECOMPUTED_45_IN,
  F413_ROUTE_PRECOMPUTED_45_OUT,
  F413_ROUTE_PRECOMPUTED_V90,
  F413_ROUTE_PRECOMPUTED_135_IN,
  F413_ROUTE_PRECOMPUTED_135_OUT,
  F413_ROUTE_PRECOMPUTED_SMALL_90,
} F413RoutePrecomputedKind;

typedef struct
{
  NfTurnSpec spec;
  NfTurnPlan plan;
  uint16_t pose_offset;
  uint16_t intervals;
} F413RoutePrecomputedGeometry;

typedef struct
{
  uint8_t case_index;
  NfTurnSpec timing[F413_ROUTE_PRECOMPUTED_SPEED_COUNT][F413_ROUTE_PRECOMPUTED_KIND_COUNT];
  NfTurnPlan timing_plan[F413_ROUTE_PRECOMPUTED_SPEED_COUNT][F413_ROUTE_PRECOMPUTED_KIND_COUNT];
  uint32_t turn_time_us[F413_ROUTE_PRECOMPUTED_SPEED_COUNT][F413_ROUTE_PRECOMPUTED_KIND_COUNT];
  NfLinearLimits orthogonal;
  NfLinearLimits diagonal;
  double speed_mm_s[F413_ROUTE_PRECOMPUTED_SPEED_COUNT];
  uint32_t start_time_us;
  /* Full linear-plan duration in microseconds. Distance is steps *
   * the firmware DIST_HALF_SEC value for ORTHOGONAL or steps *
   * DIST_D_HALF_SEC for DIAGONAL.
   * Entry indexes speed_mm_s; exit indexes NOMINAL/LOW/CRAWL or
   * zero velocity (STOP). UINT32_MAX means infeasible. Goal-cross
   * time inside a selected plan remains position-dependent. */
  uint32_t connector_time_us[F413_ROUTE_PRECOMPUTED_HEADING_CLASS_COUNT][F413_ROUTE_PRECOMPUTED_SPEED_COUNT][F413_ROUTE_PRECOMPUTED_EXIT_SPEED_COUNT][F413_ROUTE_PRECOMPUTED_CONNECTOR_STEP_COUNT];
  /* Orthogonal approach for large/small turns. At steps==0 only an
   * unchanged speed is feasible. A one-step approach uses the exact
   * constant-acceleration controller profile within DIST_HALF_SEC.
   * For steps>=2, plan
   * the leading (steps-1)*DIST_HALF_SEC to exit speed, then reserve
   * the final DIST_HALF_SEC at
   * constant speed. UINT32_MAX means infeasible. */
  uint32_t orthogonal_approach_time_us[F413_ROUTE_PRECOMPUTED_SPEED_COUNT][F413_ROUTE_PRECOMPUTED_SPEED_COUNT][F413_ROUTE_PRECOMPUTED_CONNECTOR_STEP_COUNT];
} F413RoutePrecomputedCase;

extern const char g_f413_route_precomputed_input_sha256[];
extern const NfTurnPose g_f413_route_precomputed_poses[F413_ROUTE_PRECOMPUTED_POSE_COUNT];
extern const F413RoutePrecomputedGeometry g_f413_route_precomputed_geometry[F413_ROUTE_PRECOMPUTED_KIND_COUNT];
extern const F413RoutePrecomputedCase g_f413_route_precomputed_cases[F413_ROUTE_PRECOMPUTED_CASE_COUNT];

const F413RoutePrecomputedCase*
f413_route_precomputed_find_case(uint8_t case_index);

#ifdef __cplusplus
}
#endif

#endif
