#include "sensor_distance.h"

/* Generated by tools/logging/fit_sensor_distance.py. */
void sensor_distance_load_profile_luts(void)
{
  static const uint16_t s_fr_mm[] = {
    40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95,
    100, 105, 110
  };
  static const uint16_t s_fr_ad[] = {
    1922, 1421, 1058, 799, 621, 490, 402, 331, 277, 237, 199, 174,
    149, 130, 112
  };
  (void)sensor_distance_set_lut_fr(s_fr_mm, s_fr_ad, sizeof(s_fr_mm) / sizeof(s_fr_mm[0]));

  static const uint16_t s_fl_mm[] = {
    40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95,
    100, 105, 110
  };
  static const uint16_t s_fl_ad[] = {
    2442, 1816, 1374, 1072, 861, 701, 576, 483, 409, 351, 306, 266,
    234, 208, 185
  };
  (void)sensor_distance_set_lut_fl(s_fl_mm, s_fl_ad, sizeof(s_fl_mm) / sizeof(s_fl_mm[0]));

  static const uint16_t s_front_sum_mm[] = {
    40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95,
    100, 105, 110
  };
  static const uint16_t s_front_sum_ad[] = {
    4364, 3237, 2432, 1871, 1482, 1191, 978, 814, 686, 588, 505, 440,
    383, 338, 297
  };
  (void)sensor_distance_set_lut_front_sum(s_front_sum_mm, s_front_sum_ad, sizeof(s_front_sum_mm) / sizeof(s_front_sum_mm[0]));
}
